{% set name = "shell-source" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9cf0483bec7451bca5b004789a679957473f96f7743f635e17f956fe04cacd02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - importlib-metadata >=4.11.4,<5.0.0
    - python >=3.7
    - toml >=0.10.2,<1.0.0

test:
  imports:
    - shell_source
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/abrahammurciano/python-shell-source
  summary: A python module for sourcing variables from shell scripts
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - abrahammurciano
